services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: loyalty
      POSTGRES_USER: one_chef
      POSTGRES_PASSWORD: restoranchik
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 10

  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__DefaultConnection: Host=db;Port=5432;Database=loyalty;Username=one_chef;Password=restoranchik
    ports:
      - "8080:8080"
    restart: always

volumes:
  pg_data:
