services:
  app:
    build: .
    environment:
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__DefaultConnection: Data Source=/data/loyalty.db
    ports:
      - "8080:8080"
    volumes:
          - sqlite_data:/data
    restart: always

volumes:
  sqlite_data:
